name: Sync to GitCode

on:
  push:
    branches:
      - main
jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:KingPrimes/DataSource.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
  to_gitcode_com:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitcode.com/KingPrimes/DataSource.git'
          GIT_USERNAME: KingPrimes
          GIT_PASSWORD: ${{ secrets.GIT_CODE_COM }}
  to_gitcode_net:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitcode.net/KingPrimes/DataSource.git'
          GIT_USERNAME: KingPrimes
          GIT_PASSWORD: ${{ secrets.GIT_CODE_NET }}
  to_gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitee.com/KingPrime/DataSource.git'
          GIT_USERNAME: KingPrime
          GIT_PASSWORD: ${{ secrets.GIT_EE_COM }}